from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime, Text, LargeBinary
from sqlalchemy.orm import declarative_base
import datetime

Base = declarative_base()

class Device(Base):
    __tablename__ = 'devices'
    id = Column(Integer, primary_key=True)
    client_id = Column(String(255), unique=True, nullable=False)
    first_seen = Column(DateTime, default=datetime.datetime.utcnow)
    is_quarantined = Column(Boolean, default=False)

class BaselineMetadata(Base):
    __tablename__ = 'baselines'
    id = Column(Integer, primary_key=True)
    client_id = Column(String(255), index=True, nullable=False)
    model_type = Column(String(50), nullable=False) # e.g. 'session', 'message'
    
    # Store the scikit-learn trained model as a binary blob
    model_blob = Column(LargeBinary, nullable=True)
    
    # Store the rolling window of normal events as a JSON string (for Gemini prompt)
    rolling_features_json = Column(Text, nullable=True)
    
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)

class DriftScoreHistory(Base):
    __tablename__ = 'drift_history'
    id = Column(Integer, primary_key=True)
    client_id = Column(String(255), index=True, nullable=False)
    timestamp = Column(DateTime, default=datetime.datetime.utcnow)
    anomaly_score = Column(Float, nullable=False)
    
    # The human-readable reason generated by the Gemini API
    explanation = Column(Text, nullable=True) 
    severity = Column(String(50), nullable=False) # 'normal', 'mild', 'moderate', 'severe'

class PolicyActionLog(Base):
    __tablename__ = 'action_log'
    id = Column(Integer, primary_key=True)
    client_id = Column(String(255), index=True, nullable=False)
    timestamp = Column(DateTime, default=datetime.datetime.utcnow)
    action_taken = Column(String(100), nullable=False) # 'log', 're-auth', 'quarantine'
    reason = Column(Text, nullable=True)
