#include <string.h>
#include <time.h>
#include "trustmqtt_plugin.h"

#ifdef HAVE_MOSQUITTO
#include <mosquitto.h>
#include <mosquitto_broker.h>
#include <mosquitto_plugin.h>
#endif

/* PUBLISH hook using MOSQ_EVT_MESSAGE: fires when a message is published */
int handle_publish_event(void *userdata, const void *event)
{
    (void)userdata;
    if (!event) return 0;

    device_metadata_t m;
    memset(&m, 0, sizeof(m));
    strncpy(m.event_type, "PUBLISH", sizeof(m.event_type)-1);
    m.timestamp_ms = (uint64_t)time(NULL) * 1000ULL;

#ifdef HAVE_MOSQUITTO
    const struct mosquitto_evt_message *evt = (const struct mosquitto_evt_message *)event;
    if (evt->client) {
        const char *id = mosquitto_client_id(evt->client);
        if (id) {
            strncpy(m.client_id, id, sizeof(m.client_id)-1);
        } else {
            strncpy(m.client_id, "unknown", sizeof(m.client_id)-1);
        }
    } else {
        /* Messages generated by the broker itself might not have a client */
        strncpy(m.client_id, "broker_internal", sizeof(m.client_id)-1);
    }
    
    if (evt->topic) {
        strncpy(m.topic, evt->topic, sizeof(m.topic)-1);
    } else {
        strncpy(m.topic, "unknown/topic", sizeof(m.topic)-1);
    }
    
    m.qos = evt->qos;
    m.retain = evt->retain;
    m.payload_size_bytes = evt->payloadlen;
    /* packet_id is generally internal to the client connection, we skip it for v1 */
#else
    strncpy(m.client_id, "unknown", sizeof(m.client_id)-1);
    strncpy(m.topic, "unknown/topic", sizeof(m.topic)-1);
    m.payload_size_bytes = 0;
#endif

    char *json = serialize_metadata_json(&m);
    if (json) {
        enqueue_metadata_json(json);
        free_serialized(json);
    }
    return 0;
}
