"""LLM-based incident report generation (spec §7.1), via NVIDIA NIM's
OpenAI-compatible chat-completions API. Never imports from ingest.py or
handles raw events (spec §12 rule 6) — this module only ever sees the
output of redact.py. A report must never block on the external API: any
failure, timeout, or missing key falls back to a deterministic template
renderer.
"""
from __future__ import annotations

import logging

logger = logging.getLogger(__name__)

PROMPT_TEMPLATE = """Write a concise incident report for a security operator.

Client: {client_id}
Peak verdict level: {peak_level} (score {peak_score:.2f})
Trust score components this incident: {reason}
Novel behavior transitions (FSM-diff): {fsm_diff}
Window stats: {window_stats}

Explain in 3-5 sentences what likely happened and why the automated policy
engine escalated to this level, in plain language for an operator who is
not a data scientist.
"""


def build_prompt(redacted_summary: dict) -> str:
    return PROMPT_TEMPLATE.format(
        client_id=redacted_summary.get("client_id", "unknown"),
        peak_level=redacted_summary.get("peak_level", "?"),
        peak_score=redacted_summary.get("peak_score", 0.0) or 0.0,
        reason=redacted_summary.get("reason", ""),
        fsm_diff=redacted_summary.get("fsm_diff", []),
        window_stats=redacted_summary.get("window_stats", {}),
    )


def render_fallback_report(redacted_summary: dict) -> str:
    """Deterministic template used whenever the LLM is disabled,
    unreachable, slow, or errors."""
    lines = [
        f"# Incident report: {redacted_summary.get('client_id', 'unknown')}",
        "",
        f"- Peak verdict level: {redacted_summary.get('peak_level', '?')}",
        f"- Peak trust score: {redacted_summary.get('peak_score', 0.0) or 0.0:.2f}",
        f"- Reason: {redacted_summary.get('reason', 'n/a')}",
    ]
    fsm_diff = redacted_summary.get("fsm_diff") or []
    if fsm_diff:
        lines.append("- Novel behavior transitions:")
        for d in fsm_diff:
            lines.append(f"  - {d.get('from')} -> {d.get('to')} (learned p={d.get('learned_p', 0):.4f})")
    lines.append("")
    lines.append("(Generated by the deterministic fallback renderer — the LLM was disabled or unavailable.)")
    return "\n".join(lines)


def generate_report(redacted_summary: dict, api_key: str | None, model: str,
                     timeout_s: float, enabled: bool, base_url: str) -> str:
    """Returns report markdown. Tries NVIDIA NIM first if enabled and an
    API key is configured; falls back to the deterministic renderer on any
    failure, timeout, or missing key."""
    if not enabled or not api_key:
        return render_fallback_report(redacted_summary)

    prompt = build_prompt(redacted_summary)
    try:
        from openai import OpenAI

        client = OpenAI(api_key=api_key, base_url=base_url, timeout=timeout_s)
        response = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.2,
            max_tokens=512,
        )
        text = response.choices[0].message.content
        return text if text else render_fallback_report(redacted_summary)
    except Exception as e:  # noqa: BLE001 - deliberate: the LLM must never break incident creation
        logger.warning("NVIDIA NIM report generation failed, using fallback: %s", e)
        return render_fallback_report(redacted_summary)
